<a href="https://colab.research.google.com/github/kdChen07/Financial_Engineering/blob/main/%E6%AC%A7%E6%B4%B2%E5%8F%91%E7%94%B5%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("data123.csv")
data

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,1,2,3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Country,Time,Balance,Product,Value,Unit
0,Australia,Sep-22,Net Electricity Production,Electricity,21161.5036,GWh
1,Australia,Sep-22,Net Electricity Production,Total Combustible Fuels,13777.8878,GWh
2,Australia,Sep-22,Net Electricity Production,"Coal, Peat and Manufactured Gases",9631.9664,GWh
3,Australia,Sep-22,Net Electricity Production,Oil and Petroleum Products,333.9555,GWh
4,Australia,Sep-22,Net Electricity Production,Natural Gas,3566.2116,GWh
...,...,...,...,...,...,...
927956,NaN,NaN,NaN,NaN,NaN,NaN
927957,NaN,NaN,NaN,NaN,NaN,NaN
927958,NaN,NaN,NaN,NaN,NaN,NaN
927959,NaN,NaN,NaN,NaN,NaN,NaN
927960,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data=data.dropna()
data

,Country,Time,Balance,Product,Value,Unit
0,Australia,Sep-22,Net Electricity Production,Electricity,21161.5036,GWh
1,Australia,Sep-22,Net Electricity Production,Total Combustible Fuels,13777.8878,GWh
2,Australia,Sep-22,Net Electricity Production,"Coal, Peat and Manufactured Gases",9631.9664,GWh
3,Australia,Sep-22,Net Electricity Production,Oil and Petroleum Products,333.9555,GWh
4,Australia,Sep-22,Net Electricity Production,Natural Gas,3566.2116,GWh
...,...,...,...,...,...,...
5712,Serbia,Jan-22,Net Electricity Production,Other Combustible Non-Renewables,0.3972,GWh
5713,Serbia,Jan-22,Net Electricity Production,Hydro,1056.9977,GWh
5714,Serbia,Jan-22,Net Electricity Production,Wind,91.4875,GWh
5715,Serbia,Jan-22,Net Electricity Production,Solar,0.5400,GWh
5716,Serbia,Jan-22,Net Electricity Production,"Total Renewables (Geo, Solar, Wind, Other)",1170.2859,GWh

In [48]:
result=[]

In [43]:
a=data.values

In [39]:
Europe_name="Norway","Finland","Sweden","Iceland","Denmark","Faroe Islands","Estonia","Latvia","Lithuania","Moldova","Belarus","Russia","Ukraine","Poland","Czech","Slovakia","Hungary","Germany","Austria","Switzerland","Liechtenstein","United Kingdom","Ireland","Netherlands","Belgium","Luxembourg","France","Monaco","Romania","Bulgaria","Serbia","Macedonia","Slovenia","Croatia","Montenegro","Bosnia and Herzegovina","Albania","Greece","Italy","Malta","Vatican City","San Marino","Spain","Portugal","Andorra","Gibraltar"

In [41]:
len(Europe_name)

46

In [52]:
for j in range(0,46):
  for i in range(0,5717):
    if data["Country"][i]==Europe_name[j]:
      result.append(a[i])

In [53]:
result

[array(['Norway', 'Sep-22', 'Net Electricity Production', 'Electricity',
        8649.8995, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Total Combustible Fuels', 164.0986, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 25.9944, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 54.1163, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Combustible Renewables', 20.4741, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 63.5139, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production', 'Hydro',
        7429.7407, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production', 'Wind',
        1009.6588, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production', 'Solar', 14.4857,
        'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Sep-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 8474.3592, 'GWh'],
       dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production', 'Electricity',
        10574.3975, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Total Combustible Fuels', 197.6921, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 31.4625, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 65.5001, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Combustible Renewables', 24.0101, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 76.7194, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production', 'Hydro',
        9481.4836, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production', 'Wind', 843.9339,
        'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production', 'Solar', 19.3724,
        'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Aug-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 10368.7999, 'GWh'],
       dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production', 'Electricity',
        10804.982, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Total Combustible Fuels', 217.9774, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 33.9595, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 70.6984, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Combustible Renewables', 29.7412, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 83.5783, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production', 'Hydro',
        9577.2135, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production', 'Wind', 954.1398,
        'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production', 'Solar', 23.7355,
        'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Jul-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 10584.8301, 'GWh'],
       dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production', 'Electricity',
        11633.8451, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Total Combustible Fuels', 174.9127, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 26.6933, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 55.5713, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Combustible Renewables', 26.3536, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 66.2945, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production', 'Hydro',
        10697.3172, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production', 'Wind', 704.5679,
        'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production', 'Solar', 25.1317,
        'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Jun-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 11453.3704, 'GWh'],
       dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production', 'Electricity',
        10940.6033, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Total Combustible Fuels', 108.5105, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 14.0451, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 29.2397, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Combustible Renewables', 27.5824, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 37.6434, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production', 'Hydro',
        9627.012, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production', 'Wind',
        1147.8588, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production', 'Solar', 25.3063,
        'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'May-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 10827.7595, 'GWh'],
       dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production', 'Electricity',
        11156.1373, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Total Combustible Fuels', 114.2048, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 15.6737, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 32.6302, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Combustible Renewables', 25.0469, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 40.854, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production', 'Hydro',
        10136.3391, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production', 'Wind', 854.4799,
        'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production', 'Solar', 19.1979,
        'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Apr-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 11035.0637, 'GWh'],
       dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production', 'Electricity',
        14551.8918, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Total Combustible Fuels', 121.461, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 17.394, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 36.2117, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Combustible Renewables', 23.4019, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 44.4534, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production', 'Hydro',
        12986.0218, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production', 'Wind',
        1395.3898, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production', 'Solar', 17.1035,
        'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Mar-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 14421.917, 'GWh'],
       dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Electricity',
        13037.6557, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Total Combustible Fuels', 98.0261, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 14.9837, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 31.1938, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Natural Gas',
        0.0, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Combustible Renewables', 14.662, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 37.1867, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Hydro',
        11357.8249, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Wind',
        1541.5117, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Solar', 8.3772,
        'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Feb-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 12922.3758, 'GWh'],
       dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Electricity',
        15157.7593, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Total Combustible Fuels', 114.3621, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 17.3107, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 36.0383, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Natural Gas',
        0.0, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Combustible Renewables', 17.8649, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 43.1482, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Hydro',
        13253.7457, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Wind',
        1753.3727, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Solar', 4.3632,
        'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production', 'Not Specified',
        31.9157, 'GWh'], dtype=object),
 array(['Norway', 'Jan-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 15029.3464, 'GWh'],
       dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Electricity',
        5399.0493, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Nuclear',
        2407.5584, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Total Combustible Fuels', 1394.1018, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 276.8042, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 17.4695, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Natural Gas',
        26.4498, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Combustible Renewables', 1039.7929, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 33.5854, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Hydro',
        848.7315, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Wind', 712.686,
        'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Solar',
        20.4716, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production', 'Not Specified',
        15.5, 'GWh'], dtype=object),
 array(['Finland', 'Sep-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 2621.682, 'GWh'],
       dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Electricity',
        4994.729, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Nuclear',
        1814.9133, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Total Combustible Fuels', 1184.9626, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 141.7086, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 10.2762, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Natural Gas',
        25.5051, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Combustible Renewables', 975.7192, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 31.7534, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Hydro',
        1064.4257, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Wind', 875.396,
        'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Solar',
        39.5314, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production', 'Not Specified',
        15.5, 'GWh'], dtype=object),
 array(['Finland', 'Aug-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 2955.0723, 'GWh'],
       dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Electricity',
        4531.5196, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Nuclear',
        1868.881, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Total Combustible Fuels', 1042.0746, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 72.7438, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 8.221, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Natural Gas',
        30.2283, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Combustible Renewables', 886.9153, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 43.9663, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Hydro',
        1019.2804, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Wind',
        538.4872, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Solar',
        47.2965, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production', 'Not Specified',
        15.5, 'GWh'], dtype=object),
 array(['Finland', 'Jul-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 2491.9793, 'GWh'],
       dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Electricity',
        4835.6805, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Nuclear',
        1773.9378, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Total Combustible Fuels', 1112.0621, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 140.7639, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 9.2486, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Natural Gas',
        26.4498, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Combustible Renewables', 895.9081, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 39.6918, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Hydro',
        1264.0682, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Wind',
        615.7568, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Solar',
        54.3556, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production', 'Not Specified',
        15.5, 'GWh'], dtype=object),
 array(['Finland', 'Jun-22', 'Net Electricity Production',
        'Total Renewables (Geo, Solar, Wind, Other)', 2830.0887, 'GWh'],
       dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production', 'Electricity',
        5564.6775, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production', 'Nuclear',
        1497.1036, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production',
        'Total Combustible Fuels', 1529.2858, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production',
        'Coal, Peat and Manufactured Gases', 327.8192, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production',
        'Oil and Petroleum Products', 12.3314, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production', 'Natural Gas',
        43.4532, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production',
        'Combustible Renewables', 1100.4944, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production',
        'Other Combustible Non-Renewables', 45.1876, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production', 'Hydro',
        1636.266, 'GWh'], dtype=object),
 array(['Finland', 'May-22', 'Net Electricity Production', 'Wind',
        841.3433, 'GWh'], dtype=object),

In [54]:
result_df=pd.DataFrame(result)

In [58]:
result_df.columns=["Country", "Time", "Balance", "Product", "Value", "Unit"]

In [59]:
result_df

,Country,Time,Balance,Product,Value,Units
0,Norway,Sep-22,Net Electricity Production,Electricity,8649.8995,GWh
1,Norway,Sep-22,Net Electricity Production,Total Combustible Fuels,164.0986,GWh
2,Norway,Sep-22,Net Electricity Production,"Coal, Peat and Manufactured Gases",25.9944,GWh
3,Norway,Sep-22,Net Electricity Production,Oil and Petroleum Products,54.1163,GWh
4,Norway,Sep-22,Net Electricity Production,Combustible Renewables,20.4741,GWh
...,...,...,...,...,...,...
3012,Portugal,Jan-22,Net Electricity Production,Hydro,909.4360,GWh
3013,Portugal,Jan-22,Net Electricity Production,Wind,1297.7456,GWh
3014,Portugal,Jan-22,Net Electricity Production,Solar,193.5551,GWh
3015,Portugal,Jan-22,Net Electricity Production,Geothermal,15.2120,GWh
3016,Portugal,Jan-22,Net Electricity Production,"Total Renewables (Geo, Solar, Wind, Other)",2768.4270,GWh

In [56]:
from google.colab import files

In [57]:
result_df.to_csv("data111.csv")
files.download("data111.csv")